name: Build and test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build-package-run:
    name: Build, package and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:all
      - uses: ./
        with:
          title: 'This is a test comment'
          status: ${{ job.status }}
          github_token: ${{ github.token }}
          classic_cms_url: https://classic-cms-url.com
          skylark_url: https://skylark-url.com
          launcher_url: https://launcher-url.com
          custom_id: 'my-custom-id'

  lint-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run prettier:check
      - run: npm run lint
      - run: npm test
