name: Build and commit dist
on:
  push:
    branches:
      - main
jobs:
  report:
    name: Build, package and commit the dist dir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run build:all
      - id: git_diff
        run: |
          num_changed_dist_files=$(git diff --numstat ./dist | wc -l)
          echo "::set-output name=num_changed_files::$num_changed_dist_files"
      - name: Commit dist
        if: ${{ steps.git_diff.outputs.num_changed_files > 0 }}
        run: |
          git config --global user.name 'Automated action'
          git config --global user.email 'automated-action-user@users.noreply.github.com'
          git commit -am "Update dist"
          git status
          git push
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: master
